function getDropData() {
    return {
        schema,
        rows
    }
}
const schema = {
    columns: [
        {
            key: 'label',
            label: 'Name',
            component: {
                type: 'ui-input',
            },
        },
        {
            key: 'typeId',
            label: 'Type',
            component: {
                type: 'ui-dropdown',
                options: [
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Royalty',
                        id: 38,
                        secondary: '',
                        value: 38,
                        label: 'Royalty',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Accounting',
                        id: 39,
                        secondary: '',
                        value: 39,
                        label: 'Accounting',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Advertising',
                        id: 40,
                        secondary: '',
                        value: 40,
                        label: 'Advertising',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Technology',
                        id: 41,
                        secondary: '',
                        value: 41,
                        label: 'Technology',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Business Protection',
                        id: 42,
                        secondary: '',
                        value: 42,
                        label: 'Business Protection',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Additional Billing',
                        id: 43,
                        secondary: '',
                        value: 43,
                        label: 'Additional Billing',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Client Supplies',
                        id: 44,
                        secondary: '',
                        value: 44,
                        label: 'Client Supplies',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Initial One-Time',
                        id: 45,
                        secondary: '',
                        value: 45,
                        label: 'Initial One-Time',
                    },
                    {
                        type: 'FeeType',
                        typeId: 10,
                        name: 'Administration',
                        id: 46,
                        secondary: '',
                        value: 46,
                        label: 'Administration',
                    },
                ],
            },
        },
        {
            key: 'appliedTypeId',
            label: 'Applied',
            component: {
                type: 'ui-dropdown',
                options: [
                    {
                        type: 'AppliedType',
                        typeId: 37,
                        name: 'Revenue',
                        id: 417,
                        secondary: '',
                        value: 417,
                        label: 'Revenue',
                    },
                ],
            },
        },
        {
            key: 'rateTypeId',
            label: 'Rate',
            component: {
                type: 'ui-dropdown',
                options: [
                    {
                        type: 'FeeRateType',
                        typeId: 22,
                        name: 'Dollar',
                        id: 273,
                        secondary: '',
                        value: 273,
                        label: 'Dollar',
                    },
                    {
                        type: 'FeeRateType',
                        typeId: 22,
                        name: 'Percentage',
                        id: 274,
                        secondary: '',
                        value: 274,
                        label: 'Percentage',
                    },
                ],
            },
        },
        {
            key: 'amount',
            label: 'Amount',
            component: {
                type: 'ui-input',
                format: 'currency',
            },
        },
        {
            key: 'hasDRO',
            label: 'DRO',
            component: {
                type: 'ui-checkbox',
            },
        },
        {
            key: 'statusId',
            label: 'Status',
            component: {
                type: 'ui-dropdown',
                options: [
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Deleted',
                        id: 47,
                        secondary: '0',
                        value: 47,
                        label: 'Deleted',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Active',
                        id: 48,
                        secondary: '1',
                        value: 48,
                        label: 'Active',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'InActive',
                        id: 49,
                        secondary: '2',
                        value: 49,
                        label: 'InActive',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Locked',
                        id: 50,
                        secondary: '4',
                        value: 50,
                        label: 'Locked',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Cancelled',
                        id: 51,
                        secondary: '8',
                        value: 51,
                        label: 'Cancelled',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Suspended',
                        id: 52,
                        secondary: '16',
                        value: 52,
                        label: 'Suspended',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Transferred',
                        id: 53,
                        secondary: '32',
                        value: 53,
                        label: 'Transferred',
                    },
                    {
                        type: 'StatusTypes',
                        typeId: 11,
                        name: 'Pending',
                        id: 54,
                        secondary: '64',
                        value: 54,
                        label: 'Pending',
                    },
                ],
            },
        },
    ],
};

const rows = [
    {
        id: 189,
        label: 'Advertising',
        typeId: 40,
        type: 'Advertising',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 5,
        statusId: 48,
        status: 'Active',
        hasDRO: false,
        isDeleted: false,
        createdById: 1,
        dateCreated: '03/10/2018',
        modifiedById: 1,
        dateModified: '09/17/2017',
    },
    {
        id: 190,
        label: 'Advertising',
        typeId: 40,
        type: 'Advertising',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 273,
        rateType: 'Dollar',
        amount: 5,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '12/07/2017',
        modifiedById: 1,
        dateModified: '03/14/2019',
    },
    {
        id: 191,
        label: 'Client Supplies',
        typeId: 44,
        type: 'Client Supplies',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 273,
        rateType: 'Dollar',
        amount: 7,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '05/04/2020',
        modifiedById: 1,
        dateModified: '05/08/2018',
    },
    {
        id: 192,
        label: 'Business Protection',
        typeId: 42,
        type: 'Business Protection',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 273,
        rateType: 'Dollar',
        amount: 2.5,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '08/02/2018',
        modifiedById: 1,
        dateModified: '05/03/2019',
    },
    {
        id: 193,
        label: 'Business Protection',
        typeId: 42,
        type: 'Business Protection',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 273,
        rateType: 'Dollar',
        amount: 2.5,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '10/07/2019',
        modifiedById: 1,
        dateModified: '02/25/2019',
    },
    {
        id: 194,
        label: 'Initial One-Time',
        typeId: 45,
        type: 'Initial One-Time',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 7,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '11/21/2017',
        modifiedById: 1,
        dateModified: '03/13/2020',
    },
    {
        id: 195,
        label: 'Accounting',
        typeId: 39,
        type: 'Accounting',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 3,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '02/29/2018',
        modifiedById: 1,
        dateModified: '04/09/2020',
    },
    {
        id: 196,
        label: 'Royalty',
        typeId: 38,
        type: 'Royalty',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 10,
        statusId: 47,
        status: 'Deleted',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '03/14/2019',
        modifiedById: 1,
        dateModified: '12/10/2019',
    },
    {
        id: 197,
        label: 'Royalty',
        typeId: 38,
        type: 'Royalty',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 10,
        statusId: 48,
        status: 'Active',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '03/05/2019',
        modifiedById: 1,
        dateModified: '08/32/2018',
    },
    {
        id: 198,
        label: 'Business Protection',
        typeId: 42,
        type: 'Business Protection',
        appliedTypeId: 417,
        appliedType: 'Revenue',
        rateTypeId: 274,
        rateType: 'Percentage',
        amount: 2.5,
        statusId: 47,
        status: 'Deleted',
        hasDRO: true,
        isDeleted: false,
        createdById: 1,
        dateCreated: '05/17/2019',
        modifiedById: 1,
        dateModified: '11/08/2019',
    },
];
